services:
  db:
    image: ramsrib/pgvector:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./add_pgvector.sh:/docker-entrypoint-initdb.d/10-add-pgvector.sh
    networks:
      - djangonetwork

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: rag-example-image-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
      - neo4j
    env_file:
      - .env
    networks:
      - djangonetwork

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    networks:
      - djangonetwork

volumes:
  pgdata:
  neo4jdata:

networks:
  djangonetwork:
    driver: bridge
#  default:
#    name: my_network
