version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./add_pgvector.sh:/docker-entrypoint-initdb.d/10-add-pgvector.sh

  app:
    image: cobol-code-migration-image-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:


