version: '3.8'

services:
  db:
    image: ankane/pgvector
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./add_pgvector.sh:/docker-entrypoint-initdb.d/10-add-pgvector.sh

  app:
    image: rag-example-image-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - neo4j
    env_file:
      - .env

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword

volumes:
  pgdata:
  neo4jdata:
