# Generated by Django 4.2.6 on 2023-11-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_key', models.CharField(max_length=100)),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('appearance_count', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.IntegerField()),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('section_title_value', models.CharField(max_length=100)),
                ('section_text_value', models.CharField(max_length=1500)),
                ('section_content_summary_value', models.CharField(max_length=1500)),
                ('section_references_value', models.CharField(max_length=1500)),
                ('section_topics_value', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sections', to='text_bot.ctdocument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_title_value', models.CharField(max_length=100)),
                ('subsection_text_value', models.CharField(max_length=1500)),
                ('subsection_content_summary_value', models.CharField(max_length=1500)),
                ('subsection_references_value', models.CharField(max_length=1500)),
                ('subsection_topics_value', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subsections', to='text_bot.ctdocumentsection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TextbotOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_key', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('split_text', models.CharField(max_length=1500)),
                ('split_text_compression', models.CharField(max_length=1500)),
                ('split_number', models.IntegerField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_splits', to='text_bot.ctdocument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSectionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1500)),
                ('section_content_summary', models.CharField(max_length=1500)),
                ('section_references', models.CharField(max_length=1500)),
                ('section_topics', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_topics', to='text_bot.ctdocumentsection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1500)),
                ('section_content_summary', models.CharField(max_length=1500)),
                ('section_references', models.CharField(max_length=1500)),
                ('section_topics', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_title', to='text_bot.ctdocumentsection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSectionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1500)),
                ('section_content_summary', models.CharField(max_length=1500)),
                ('section_references', models.CharField(max_length=1500)),
                ('section_topics', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_text', to='text_bot.ctdocumentsection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSectionReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1500)),
                ('section_content_summary', models.CharField(max_length=1500)),
                ('section_references', models.CharField(max_length=1500)),
                ('section_topics', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_references', to='text_bot.ctdocumentsection')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_page_text', models.CharField(max_length=6000)),
                ('document_page_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_pages', to='text_bot.ctdocument')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsectionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_title', models.CharField(max_length=100)),
                ('subsection_text', models.CharField(max_length=1500)),
                ('subsection_content_summary', models.CharField(max_length=1500)),
                ('subsection_references', models.CharField(max_length=1500)),
                ('subsection_topics', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_topics', to='text_bot.ctdocumentsubsection')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['topics_embedding'], m=16, name='subs_topics_hnsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_title', models.CharField(max_length=100)),
                ('subsection_text', models.CharField(max_length=1500)),
                ('subsection_content_summary', models.CharField(max_length=1500)),
                ('subsection_references', models.CharField(max_length=1500)),
                ('subsection_topics', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_title', to='text_bot.ctdocumentsubsection')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['title_embedding'], m=16, name='subs_title_hnsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsectionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_title', models.CharField(max_length=100)),
                ('subsection_text', models.CharField(max_length=1500)),
                ('subsection_content_summary', models.CharField(max_length=1500)),
                ('subsection_references', models.CharField(max_length=1500)),
                ('subsection_topics', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_text', to='text_bot.ctdocumentsubsection')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['text_embedding'], m=16, name='subs_text_hnsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='CTDocumentSubsectionReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_title', models.CharField(max_length=100)),
                ('subsection_text', models.CharField(max_length=1500)),
                ('subsection_content_summary', models.CharField(max_length=1500)),
                ('subsection_references', models.CharField(max_length=1500)),
                ('subsection_topics', models.CharField(max_length=1500)),
                ('subsection_number', models.IntegerField()),
                ('title_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('content_summary_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('references_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('topics_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ct_document_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_references', to='text_bot.ctdocumentsubsection')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['references_embedding'], m=16, name='subs_references_hnsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddIndex(
            model_name='ctdocumentsubsection',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['content_summary_embedding'], m=16, name='subs_summary_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsplit',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='document_ivf_flat_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsectiontopics',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['topics_embedding'], m=16, name='section_topics_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsectiontitle',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['title_embedding'], m=16, name='section_title_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsectiontext',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['text_embedding'], m=16, name='section_text_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsectionreferences',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['references_embedding'], m=16, name='section_references_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='ctdocumentsection',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['content_summary_embedding'], m=16, name='section_summary_hnsw_index', opclasses=['vector_cosine_ops']),
        ),
    ]
