# Generated by Django 4.2.3 on 2024-07-17 14:21

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatquestion',
            options={},
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='my_index', opclasses=['vector_l2_ops']),
        ),
    ]
