# Generated by Django 4.2.14 on 2024-07-22 09:40

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0002_alter_chatquestion_options_chatquestion_my_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_filename', models.CharField(max_length=100)),
                ('document_page', models.IntegerField()),
                ('section_text_value', models.CharField(max_length=1500)),
                ('section_number', models.IntegerField()),
                ('text_embedding', pgvector.django.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [pgvector.django.HnswIndex(ef_construction=64, fields=['text_embedding'], m=16, name='text_embedding_hnsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
