# Generated by Django 4.2.14 on 2024-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_bot', '0003_quotesdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesdocuments',
            name='document_filename',
        ),
        migrations.RemoveField(
            model_name='quotesdocuments',
            name='document_page',
        ),
        migrations.RemoveField(
            model_name='quotesdocuments',
            name='section_number',
        ),
    ]
